"""add organization and workflow fields

Revision ID: 167b657a8a77
Revises: 39f7aea9e03b
Create Date: 2026-09-29 07:14:16.303329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167b657a8a77'
down_revision: Union[str, Sequence[str], None] = '39f7aea9e03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('workflow_domain', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workflow_domain')
    op.drop_column('users', 'organization')
    # ### end Alembic commands ###
