"""add calendar approval fields

Revision ID: 17d5ca29e054
Revises: 364921e48fed
Create Date: 2026-10-06 11:08:06.492974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d5ca29e054'
down_revision: Union[str, Sequence[str], None] = '364921e48fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('approval_deadline', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column(
    'documents',
    sa.Column(
        'calendar_event_created',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'calendar_event_created')
    op.drop_column('documents', 'calendar_event_id')
    op.drop_column('documents', 'approval_deadline')
    # ### end Alembic commands ###
