"""add rejection reason to documents

Revision ID: ffcb0c9ea97a
Revises: a5dc4e6130a1
Create Date: 2026-10-04 06:52:05.347460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcb0c9ea97a'
down_revision: Union[str, Sequence[str], None] = 'a5dc4e6130a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('rejection_reason', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'rejection_reason')
    # ### end Alembic commands ###
